// <auto-generated />
using HS_Stat_Tracker_DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HS_Stat_Tracker_DAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210702193201_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HS_Stat_Tracker_Domain.Card", b =>
                {
                    b.Property<int>("dbfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cardClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("collectible")
                        .HasColumnType("bit");

                    b.Property<int>("cost")
                        .HasColumnType("int");

                    b.Property<string>("flavor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dbfId");

                    b.ToTable("Cards");

                    b.HasDiscriminator<string>("type").HasValue("Card");
                });

            modelBuilder.Entity("HS_Stat_Tracker_Domain.Deck", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("HS_Stat_Tracker_Domain.Minion", b =>
                {
                    b.HasBaseType("HS_Stat_Tracker_Domain.Card");

                    b.Property<int>("attack")
                        .HasColumnType("int");

                    b.Property<int>("health")
                        .HasColumnType("int");

                    b.Property<string>("race")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("minion");
                });

            modelBuilder.Entity("HS_Stat_Tracker_Domain.Spell", b =>
                {
                    b.HasBaseType("HS_Stat_Tracker_Domain.Card");

                    b.HasDiscriminator().HasValue("spell");
                });
#pragma warning restore 612, 618
        }
    }
}
